### ISSUE TITLE
Speed of Diffusion probabilistic models

### ISSUE THREAD

**Issue by ofirkris** [andreas128/RePaint#2]
Great work - results look very impressive.
From my experience Diffusion Models are quite heavy in terms of computation, can you share info about the inference speed?

**Comment by world2vec** [comment]
Also interested, looks it is too slow to really use it.

**Comment by Mut1nyJD** [comment]
@world2vec and @ofirkris If you think diffusion models are too slow you might want to check out this ICLR2022 submission then
https://openreview.net/pdf?id=TIdIXIpzhoI from Google Brain team.

**Comment by andreas128** [comment]
Thanks a lot! Speed is a major issue, we put some ideas together to increase the speed of our inference schedule https://github.com/andreas128/RePaint#adapt-the-code

Does that help?
