### ISSUE TITLE
how to get celeba256_250000.pt?

### ISSUE THREAD

**Issue by pokameng** [andreas128/RePaint#21]
hello!
thanks for your great works
I want to know  how to get celeba256_250000.pt?
I use guide-diffusion to save model, but something was wrong like this:

![74a4264d3e8f653e402acf63bb6621f](https://user-images.githubusercontent.com/47957015/194762235-ea8077ac-1cf0-42f4-855f-68311db1f0bd.jpg)

Can you give me some suggesstions?
thanks alot!
@andreas128 @freddy1020

**Comment by andreas128** [comment]
It seems that the model architecture has changed. Can you try the following?

**Option 1:**
Try to use the model code from your training by copying it [here](https://github.com/andreas128/RePaint/blob/main/guided_diffusion/unet.py).

**Option 2:**
Download the model using this script. 

```
pip install --upgrade gdown && bash ./download.sh
```

**Option 3:**
Download the model directly from google drive: https://drive.google.com/uc?id=1norNWWGYP3EZ_o05DmoW1ryKuKMmhlCX

**Comment by pokameng** [comment]
ok thanks!
