### ISSUE TITLE
Is it Windows "friendly"? Issue with double ampersand.

### ISSUE THREAD

**Issue by cibernicola** [andreas128/RePaint#5]
I''m trying to check this piece of work, but I'm seeing, for example, 

`pip install --upgrade gdown && bash ./download.sh`

The double ampersand in visualstudio code in Windows, using PowerShell as terminal doesn't work (some kinda mess with PS and double &), to run it use CMD intead, anyway, the first question remains, do you know if it is Windows OS, friendly? 

Thanks!

**Comment by andreas128** [comment]
The command first installs the pip package `gdown` and then runs the shell script `download.sh`

Does it work if you split it in two commands?

1.) Install the package gdown, which is a command line tool to download from google drive.
```
pip install --upgrade gdown
```

2.) Run the download script.
```
bash ./download.sh
```

Alternative:
If this does not work, you can download the files manually using the links in `download.sh`

**Comment by cibernicola** [comment]
It's working :)
