### ISSUE TITLE
Great work, When will you relase the train code?

### ISSUE THREAD

**Issue by zhangbaijin** [andreas128/RePaint#8]

**Comment by ExponentialML** [comment]
Get the training parameters here: https://github.com/openai/improved-diffusion
Use the repository here to train: https://github.com/openai/guided-diffusion

You don't need to train a classifier, but you can if you wish. The `image_train.py` exists in both repositories, but I believe `guided-diffusion` has better optimizations for training than the `improved-diffusion` one, so use that repository instead.

**Comment by andreas128** [comment]
@ExponentialML thanks for answering.

**Comment by pfeducode** [comment]
Do you mean to replace the training code of this project with the training file in guided-diffusion directly？

**Comment by Hydrageno** [comment]
> 

I have the same question, do u solve it?

**Comment by Hydrageno** [comment]
> Do you mean to replace the training code of this project with the training file in guided-diffusion directly？

I have the same question, do u solve it?

**Comment by pfeducode** [comment]
> > 你的意思是直接用guided-diffusion中的训练文件替换本项目的训练代码？
> 
> 我有同样的问题，你解决了吗？

I have only tested the code for guided diffusion. The author of this repository has provided the parameter configuration for diffusion in document [face_example.yml](https://github.com/andreas128/RePaint/blob/main/confs/face_example.yml), which I believe can be replicated. However, you need to organize the code according to the methods in the RePaint paper, such as adding masks to images.

**Comment by Hydrageno** [comment]
> 


> > > 你的意思是直接用guided-diffusion中的训练文件替换本项目的训练代码？
> > 
> > 
> > 我有同样的问题，你解决了吗？
> 
> I have only tested the code for guided diffusion. The author of this repository has provided the parameter configuration for diffusion in document [face_example.yml](https://github.com/andreas128/RePaint/blob/main/confs/face_example.yml), which I believe can be replicated. However, you need to organize the code according to the methods in the RePaint paper, such as adding masks to images.


thank u, I failed to train my diffusion model yesterday.

**Comment by pfeducode** [comment]
> > 
> 
> > > > 你的意思是直接用guided-diffusion中的训练文件代替本项目的训练代号？
> > > 
> > > 
> > > 我有同样的问题，你解决了吗？
> > 
> > 
> > 我只测试了引导扩散的代码。本仓库作者在文档[face_example.yml](https://github.com/andreas128/RePaint/blob/main/confs/face_example.yml)中提供了diffusion的参数配置，相信可以复制。但是，你需要按照RePaint论文中的方法来组织代码，比如给图像添加遮罩。
> 
> 谢谢你，我昨天没有训练我的扩散模型。
you are welcome

**Comment by jbnjvc10000** [comment]
> > > 
> > 
> > 
> > > > > 你的意思是直接用guided-diffusion中的训练文件代替本项目的训练代号？
> > > > 
> > > > 
> > > > 我有同样的问题，你解决了吗？
> > > 
> > > 
> > > 我只测试了引导扩散的代码。本仓库作者在文档[face_example.yml](https://github.com/andreas128/RePaint/blob/main/confs/face_example.yml)中提供了diffusion的参数配置，相信可以复制。但是，你需要按照RePaint论文中的方法来组织代码，比如给图像添加遮罩。
> > 
> > 
> > 谢谢你，我昨天没有训练我的扩散模型。
> > you are welcome

Excuse me, I actually need to train two models if i want repaint another dataset?
